### ISSUE TITLE
Different URL on prod/dev

### ISSUE THREAD

**Issue by seysn** [ludovicOuvry/BasketFront#1]
We want different url in the file [data.service.ts
](https://github.com/ludovicOuvry/BasketFront/blob/master/src/app/data.service.ts#L15).

When we're working on the prod environment, we want a url such as `basketback:3306` instead of `localhost:8080/`.

**Comment by ludovicOuvry** [comment]
done,
you can put the url in  environement file (alredy done for production) and you can start whit ng build -c  production
