### ISSUE TITLE
Cannot POST from the website

### ISSUE THREAD

**Issue by seysn** [ludovicOuvry/BasketFront#2]
Maybe related to #1.

POST is working in backend, but we get js error while trying to POST from the website.

**Comment by ludovicOuvry** [comment]
c'est OK avec le réglement du problème post  d'hier ?

**Comment by seysn** [comment]
Non justement, c'est ce que je dis sur le premier message : Sur le back ca marche bien, mais quand on essaye de faire un post via le site front, on se mange des erreurs. 
Mais comme je dis c'est peut-être a cause du problème de l'issue #1, du fait que l'application cherche dans localhost au lieu d'une adresse fixée.
